package tam;

/**
 * This enum provides a list of all the user interface
 * text that needs to be loaded from the XML properties
 * file. By simply changing the XML file we could initialize
 * this application such that all UI controls are provided
 * in another language.
 * 
 * @author Richard McKenna
 * @version 1.0
 */
public enum TAManagerProp {
    // FOR SIMPLE OK/CANCEL DIALOG BOXES
    OK_PROMPT,
    CANCEL_PROMPT,
    
    // THESE ARE FOR TEXT PARTICULAR TO THE APP'S WORKSPACE CONTROLS
    TAS_HEADER_TEXT,
    NAME_COLUMN_TEXT,
    EMAIL_COLUMN_TEXT,
    NAME_PROMPT_TEXT,
    EMAIL_PROMPT_TEXT,
    ADD_BUTTON_TEXT,
    CLEAR_BUTTON_TEXT,
    OFFICE_HOURS_SUBHEADER,
    OFFICE_HOURS_TABLE_HEADERS,
    DAYS_OF_WEEK,
    
    // THESE ARE FOR ERROR MESSAGES PARTICULAR TO THE APP
    MISSING_TA_NAME_TITLE,
    MISSING_TA_NAME_MESSAGE,
    MISSING_TA_EMAIL_TITLE,
    MISSING_TA_EMAIL_MESSAGE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_TITLE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_MESSAGE,
    EMAIL_ADDRESS_NOT_VALID,
    EMAIL_ADDRESS_NOT_VALID_MESSAGE,
    TA_NOT_CHANGED_TITLE,
    TA_NOT_CHANGED_MESSAGE,
    INVALID_START_HOUR_TITLE,
    INVALID_START_HOUR_MESSAGE,
    INVALID_END_HOUR_TITLE,
    INVALID_END_HOUR_MESSAGE,
    
    // FILE PATHS
    SYLLABUS,
    JS_GRID_BUILDER,
    JS_RECITATIONS_BUILDER,
    JS_RECITATIONS_DATA,
    SYLLABUS_PATH,
    JS_GRID_BUILDER_PATH,
    JS_OFFICE_HOURS_PATH,
    JS_RECITATIONS_BUILDER_PATH,
    JS_RECITATIONS_DATA_PATH,
    JS_FOLDER,
    CSS_FOLDER,
    IMAGES_FOLDER,
    TA_TOBE_DELETED_MESSAGE,
    CONTINUE_TITLE
}
